package de.sj4.coronapartyapp.util

enum class DeviceUIState {
    UNPAIRED,
    PAIRED_NO_RESULT,
    PAIRED_POSITIVE,
    PAIRED_POSITIVE_TELETAN,
    PAIRED_NEGATIVE,
    PAIRED_ERROR,
    SUBMITTED_INITIAL,
    SUBMITTED_FINAL
}
